/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewIndexRouteImport } from './routes/view/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ScoreProfilesIndexRouteImport } from './routes/score-profiles/index'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as TournamentsNewRouteImport } from './routes/tournaments/new'
import { Route as TeamsNewRouteImport } from './routes/teams/new'
import { Route as ScoreProfilesNewRouteImport } from './routes/score-profiles/new'
import { Route as ScoreProfilesScoreProfileIdRouteImport } from './routes/score-profiles/$scoreProfileId'
import { Route as MatchesMatchIdRouteImport } from './routes/matches/$matchId'
import { Route as ViewTournamentIdIndexRouteImport } from './routes/view/$tournamentId/index'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as TeamsSlugIndexRouteImport } from './routes/teams/$slug/index'
import { Route as TournamentsTournamentIdRegisterRouteImport } from './routes/tournaments/$tournamentId/register'
import { Route as TournamentsTournamentIdFieldRolesRouteImport } from './routes/tournaments/$tournamentId/field-roles'
import { Route as TournamentsTournamentIdEditRouteImport } from './routes/tournaments/$tournamentId/edit'
import { Route as TeamsSlugEditRouteImport } from './routes/teams/$slug/edit'
import { Route as ViewTournamentIdStageIdIndexRouteImport } from './routes/view/$tournamentId/$stageId/index'
import { Route as TournamentsTournamentIdStagesIndexRouteImport } from './routes/tournaments/$tournamentId/stages/index'
import { Route as TournamentsTournamentIdStagesNewRouteImport } from './routes/tournaments/$tournamentId/stages/new'
import { Route as TournamentsTournamentIdStagesStageIdLiveRouteImport } from './routes/tournaments/$tournamentId/stages/$stageId/live'
import { Route as TournamentsTournamentIdStagesStageIdEditRouteImport } from './routes/tournaments/$tournamentId/stages/$stageId/edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/view/',
  path: '/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreProfilesIndexRoute = ScoreProfilesIndexRouteImport.update({
  id: '/score-profiles/',
  path: '/score-profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsNewRoute = TournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/teams/new',
  path: '/teams/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreProfilesNewRoute = ScoreProfilesNewRouteImport.update({
  id: '/score-profiles/new',
  path: '/score-profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreProfilesScoreProfileIdRoute =
  ScoreProfilesScoreProfileIdRouteImport.update({
    id: '/score-profiles/$scoreProfileId',
    path: '/score-profiles/$scoreProfileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTournamentIdIndexRoute = ViewTournamentIdIndexRouteImport.update({
  id: '/view/$tournamentId/',
  path: '/view/$tournamentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/tournaments/$tournamentId/',
    path: '/tournaments/$tournamentId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsSlugIndexRoute = TeamsSlugIndexRouteImport.update({
  id: '/teams/$slug/',
  path: '/teams/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRegisterRoute =
  TournamentsTournamentIdRegisterRouteImport.update({
    id: '/tournaments/$tournamentId/register',
    path: '/tournaments/$tournamentId/register',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdFieldRolesRoute =
  TournamentsTournamentIdFieldRolesRouteImport.update({
    id: '/tournaments/$tournamentId/field-roles',
    path: '/tournaments/$tournamentId/field-roles',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdEditRoute =
  TournamentsTournamentIdEditRouteImport.update({
    id: '/tournaments/$tournamentId/edit',
    path: '/tournaments/$tournamentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsSlugEditRoute = TeamsSlugEditRouteImport.update({
  id: '/teams/$slug/edit',
  path: '/teams/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewTournamentIdStageIdIndexRoute =
  ViewTournamentIdStageIdIndexRouteImport.update({
    id: '/view/$tournamentId/$stageId/',
    path: '/view/$tournamentId/$stageId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdStagesIndexRoute =
  TournamentsTournamentIdStagesIndexRouteImport.update({
    id: '/tournaments/$tournamentId/stages/',
    path: '/tournaments/$tournamentId/stages/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdStagesNewRoute =
  TournamentsTournamentIdStagesNewRouteImport.update({
    id: '/tournaments/$tournamentId/stages/new',
    path: '/tournaments/$tournamentId/stages/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdStagesStageIdLiveRoute =
  TournamentsTournamentIdStagesStageIdLiveRouteImport.update({
    id: '/tournaments/$tournamentId/stages/$stageId/live',
    path: '/tournaments/$tournamentId/stages/$stageId/live',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdStagesStageIdEditRoute =
  TournamentsTournamentIdStagesStageIdEditRouteImport.update({
    id: '/tournaments/$tournamentId/stages/$stageId/edit',
    path: '/tournaments/$tournamentId/stages/$stageId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/score-profiles/$scoreProfileId': typeof ScoreProfilesScoreProfileIdRoute
  '/score-profiles/new': typeof ScoreProfilesNewRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/results': typeof ResultsIndexRoute
  '/score-profiles': typeof ScoreProfilesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/view': typeof ViewIndexRoute
  '/teams/$slug/edit': typeof TeamsSlugEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId/field-roles': typeof TournamentsTournamentIdFieldRolesRoute
  '/tournaments/$tournamentId/register': typeof TournamentsTournamentIdRegisterRoute
  '/teams/$slug': typeof TeamsSlugIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/view/$tournamentId': typeof ViewTournamentIdIndexRoute
  '/tournaments/$tournamentId/stages/new': typeof TournamentsTournamentIdStagesNewRoute
  '/tournaments/$tournamentId/stages': typeof TournamentsTournamentIdStagesIndexRoute
  '/view/$tournamentId/$stageId': typeof ViewTournamentIdStageIdIndexRoute
  '/tournaments/$tournamentId/stages/$stageId/edit': typeof TournamentsTournamentIdStagesStageIdEditRoute
  '/tournaments/$tournamentId/stages/$stageId/live': typeof TournamentsTournamentIdStagesStageIdLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/score-profiles/$scoreProfileId': typeof ScoreProfilesScoreProfileIdRoute
  '/score-profiles/new': typeof ScoreProfilesNewRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/results': typeof ResultsIndexRoute
  '/score-profiles': typeof ScoreProfilesIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/view': typeof ViewIndexRoute
  '/teams/$slug/edit': typeof TeamsSlugEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId/field-roles': typeof TournamentsTournamentIdFieldRolesRoute
  '/tournaments/$tournamentId/register': typeof TournamentsTournamentIdRegisterRoute
  '/teams/$slug': typeof TeamsSlugIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/view/$tournamentId': typeof ViewTournamentIdIndexRoute
  '/tournaments/$tournamentId/stages/new': typeof TournamentsTournamentIdStagesNewRoute
  '/tournaments/$tournamentId/stages': typeof TournamentsTournamentIdStagesIndexRoute
  '/view/$tournamentId/$stageId': typeof ViewTournamentIdStageIdIndexRoute
  '/tournaments/$tournamentId/stages/$stageId/edit': typeof TournamentsTournamentIdStagesStageIdEditRoute
  '/tournaments/$tournamentId/stages/$stageId/live': typeof TournamentsTournamentIdStagesStageIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/score-profiles/$scoreProfileId': typeof ScoreProfilesScoreProfileIdRoute
  '/score-profiles/new': typeof ScoreProfilesNewRoute
  '/teams/new': typeof TeamsNewRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/results/': typeof ResultsIndexRoute
  '/score-profiles/': typeof ScoreProfilesIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/view/': typeof ViewIndexRoute
  '/teams/$slug/edit': typeof TeamsSlugEditRoute
  '/tournaments/$tournamentId/edit': typeof TournamentsTournamentIdEditRoute
  '/tournaments/$tournamentId/field-roles': typeof TournamentsTournamentIdFieldRolesRoute
  '/tournaments/$tournamentId/register': typeof TournamentsTournamentIdRegisterRoute
  '/teams/$slug/': typeof TeamsSlugIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/view/$tournamentId/': typeof ViewTournamentIdIndexRoute
  '/tournaments/$tournamentId/stages/new': typeof TournamentsTournamentIdStagesNewRoute
  '/tournaments/$tournamentId/stages/': typeof TournamentsTournamentIdStagesIndexRoute
  '/view/$tournamentId/$stageId/': typeof ViewTournamentIdStageIdIndexRoute
  '/tournaments/$tournamentId/stages/$stageId/edit': typeof TournamentsTournamentIdStagesStageIdEditRoute
  '/tournaments/$tournamentId/stages/$stageId/live': typeof TournamentsTournamentIdStagesStageIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/matches/$matchId'
    | '/score-profiles/$scoreProfileId'
    | '/score-profiles/new'
    | '/teams/new'
    | '/tournaments/new'
    | '/results'
    | '/score-profiles'
    | '/teams'
    | '/tournaments'
    | '/view'
    | '/teams/$slug/edit'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId/field-roles'
    | '/tournaments/$tournamentId/register'
    | '/teams/$slug'
    | '/tournaments/$tournamentId'
    | '/view/$tournamentId'
    | '/tournaments/$tournamentId/stages/new'
    | '/tournaments/$tournamentId/stages'
    | '/view/$tournamentId/$stageId'
    | '/tournaments/$tournamentId/stages/$stageId/edit'
    | '/tournaments/$tournamentId/stages/$stageId/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/matches/$matchId'
    | '/score-profiles/$scoreProfileId'
    | '/score-profiles/new'
    | '/teams/new'
    | '/tournaments/new'
    | '/results'
    | '/score-profiles'
    | '/teams'
    | '/tournaments'
    | '/view'
    | '/teams/$slug/edit'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId/field-roles'
    | '/tournaments/$tournamentId/register'
    | '/teams/$slug'
    | '/tournaments/$tournamentId'
    | '/view/$tournamentId'
    | '/tournaments/$tournamentId/stages/new'
    | '/tournaments/$tournamentId/stages'
    | '/view/$tournamentId/$stageId'
    | '/tournaments/$tournamentId/stages/$stageId/edit'
    | '/tournaments/$tournamentId/stages/$stageId/live'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/matches/$matchId'
    | '/score-profiles/$scoreProfileId'
    | '/score-profiles/new'
    | '/teams/new'
    | '/tournaments/new'
    | '/results/'
    | '/score-profiles/'
    | '/teams/'
    | '/tournaments/'
    | '/view/'
    | '/teams/$slug/edit'
    | '/tournaments/$tournamentId/edit'
    | '/tournaments/$tournamentId/field-roles'
    | '/tournaments/$tournamentId/register'
    | '/teams/$slug/'
    | '/tournaments/$tournamentId/'
    | '/view/$tournamentId/'
    | '/tournaments/$tournamentId/stages/new'
    | '/tournaments/$tournamentId/stages/'
    | '/view/$tournamentId/$stageId/'
    | '/tournaments/$tournamentId/stages/$stageId/edit'
    | '/tournaments/$tournamentId/stages/$stageId/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  ScoreProfilesScoreProfileIdRoute: typeof ScoreProfilesScoreProfileIdRoute
  ScoreProfilesNewRoute: typeof ScoreProfilesNewRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TournamentsNewRoute: typeof TournamentsNewRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  ScoreProfilesIndexRoute: typeof ScoreProfilesIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  ViewIndexRoute: typeof ViewIndexRoute
  TeamsSlugEditRoute: typeof TeamsSlugEditRoute
  TournamentsTournamentIdEditRoute: typeof TournamentsTournamentIdEditRoute
  TournamentsTournamentIdFieldRolesRoute: typeof TournamentsTournamentIdFieldRolesRoute
  TournamentsTournamentIdRegisterRoute: typeof TournamentsTournamentIdRegisterRoute
  TeamsSlugIndexRoute: typeof TeamsSlugIndexRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  ViewTournamentIdIndexRoute: typeof ViewTournamentIdIndexRoute
  TournamentsTournamentIdStagesNewRoute: typeof TournamentsTournamentIdStagesNewRoute
  TournamentsTournamentIdStagesIndexRoute: typeof TournamentsTournamentIdStagesIndexRoute
  ViewTournamentIdStageIdIndexRoute: typeof ViewTournamentIdStageIdIndexRoute
  TournamentsTournamentIdStagesStageIdEditRoute: typeof TournamentsTournamentIdStagesStageIdEditRoute
  TournamentsTournamentIdStagesStageIdLiveRoute: typeof TournamentsTournamentIdStagesStageIdLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/': {
      id: '/view/'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-profiles/': {
      id: '/score-profiles/'
      path: '/score-profiles'
      fullPath: '/score-profiles'
      preLoaderRoute: typeof ScoreProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/new': {
      id: '/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof TournamentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/teams/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-profiles/new': {
      id: '/score-profiles/new'
      path: '/score-profiles/new'
      fullPath: '/score-profiles/new'
      preLoaderRoute: typeof ScoreProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-profiles/$scoreProfileId': {
      id: '/score-profiles/$scoreProfileId'
      path: '/score-profiles/$scoreProfileId'
      fullPath: '/score-profiles/$scoreProfileId'
      preLoaderRoute: typeof ScoreProfilesScoreProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$tournamentId/': {
      id: '/view/$tournamentId/'
      path: '/view/$tournamentId'
      fullPath: '/view/$tournamentId'
      preLoaderRoute: typeof ViewTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug/': {
      id: '/teams/$slug/'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/register': {
      id: '/tournaments/$tournamentId/register'
      path: '/tournaments/$tournamentId/register'
      fullPath: '/tournaments/$tournamentId/register'
      preLoaderRoute: typeof TournamentsTournamentIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/field-roles': {
      id: '/tournaments/$tournamentId/field-roles'
      path: '/tournaments/$tournamentId/field-roles'
      fullPath: '/tournaments/$tournamentId/field-roles'
      preLoaderRoute: typeof TournamentsTournamentIdFieldRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/edit': {
      id: '/tournaments/$tournamentId/edit'
      path: '/tournaments/$tournamentId/edit'
      fullPath: '/tournaments/$tournamentId/edit'
      preLoaderRoute: typeof TournamentsTournamentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug/edit': {
      id: '/teams/$slug/edit'
      path: '/teams/$slug/edit'
      fullPath: '/teams/$slug/edit'
      preLoaderRoute: typeof TeamsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$tournamentId/$stageId/': {
      id: '/view/$tournamentId/$stageId/'
      path: '/view/$tournamentId/$stageId'
      fullPath: '/view/$tournamentId/$stageId'
      preLoaderRoute: typeof ViewTournamentIdStageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/stages/': {
      id: '/tournaments/$tournamentId/stages/'
      path: '/tournaments/$tournamentId/stages'
      fullPath: '/tournaments/$tournamentId/stages'
      preLoaderRoute: typeof TournamentsTournamentIdStagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/stages/new': {
      id: '/tournaments/$tournamentId/stages/new'
      path: '/tournaments/$tournamentId/stages/new'
      fullPath: '/tournaments/$tournamentId/stages/new'
      preLoaderRoute: typeof TournamentsTournamentIdStagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/stages/$stageId/live': {
      id: '/tournaments/$tournamentId/stages/$stageId/live'
      path: '/tournaments/$tournamentId/stages/$stageId/live'
      fullPath: '/tournaments/$tournamentId/stages/$stageId/live'
      preLoaderRoute: typeof TournamentsTournamentIdStagesStageIdLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/stages/$stageId/edit': {
      id: '/tournaments/$tournamentId/stages/$stageId/edit'
      path: '/tournaments/$tournamentId/stages/$stageId/edit'
      fullPath: '/tournaments/$tournamentId/stages/$stageId/edit'
      preLoaderRoute: typeof TournamentsTournamentIdStagesStageIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  ScoreProfilesScoreProfileIdRoute: ScoreProfilesScoreProfileIdRoute,
  ScoreProfilesNewRoute: ScoreProfilesNewRoute,
  TeamsNewRoute: TeamsNewRoute,
  TournamentsNewRoute: TournamentsNewRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  ScoreProfilesIndexRoute: ScoreProfilesIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  ViewIndexRoute: ViewIndexRoute,
  TeamsSlugEditRoute: TeamsSlugEditRoute,
  TournamentsTournamentIdEditRoute: TournamentsTournamentIdEditRoute,
  TournamentsTournamentIdFieldRolesRoute:
    TournamentsTournamentIdFieldRolesRoute,
  TournamentsTournamentIdRegisterRoute: TournamentsTournamentIdRegisterRoute,
  TeamsSlugIndexRoute: TeamsSlugIndexRoute,
  TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
  ViewTournamentIdIndexRoute: ViewTournamentIdIndexRoute,
  TournamentsTournamentIdStagesNewRoute: TournamentsTournamentIdStagesNewRoute,
  TournamentsTournamentIdStagesIndexRoute:
    TournamentsTournamentIdStagesIndexRoute,
  ViewTournamentIdStageIdIndexRoute: ViewTournamentIdStageIdIndexRoute,
  TournamentsTournamentIdStagesStageIdEditRoute:
    TournamentsTournamentIdStagesStageIdEditRoute,
  TournamentsTournamentIdStagesStageIdLiveRoute:
    TournamentsTournamentIdStagesStageIdLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
